# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:48
from __future__ import unicode_literals

from django.db import migrations
import machina.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum_member', '0003_auto_20160227_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='avatar',
            field=machina.models.fields.ExtendedImageField(blank=True, null=True, upload_to='forum/avatar', verbose_name='Avatar'),
        ),
    ]
